[package]
name = "btv"
version = "0.1.0"
authors = ["Joshua Chin <joshuarchin@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.2.1"
clap = "3.0.0-beta.2"
itertools = "0.10.1"